<a href="https://colab.research.google.com/github/gopaldatt/Python-Data-Science/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
#2D
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
#3D
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
#change data type
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [7]:
np.arange(1,22,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [8]:
np.arange(22)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [9]:
np.zeros((4,5) ,dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
np.ones((4,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [12]:
np.identity(2 ,dtype=int)


array([[1, 0],
       [0, 1]])

Attributes


In [13]:
a1=np.arange(12 ,dtype=int)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
a2=np.arange(12 ,dtype=int).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
a3=np.arange(8,dtype=int).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
a3.ndim

3

In [20]:
a2.ndim

2

In [21]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(12,)
(3, 4)
(2, 2, 2)


In [22]:
print(a2.size)
a2

12


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
a1.itemsize

8

In [27]:
print(a2.dtype)
print(a3.dtype)

int64
int64


In [30]:
#changing data type
a2.astype(np.int32)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)