<a href="https://colab.research.google.com/github/gopaldatt/Python-Data-Science/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
a1=np.arange(12,dtype=int)
a2=np.arange(12,dtype=int).reshape(3,4)
a3=np.arange(12,24,dtype=int).reshape(3,4)
a3
a3.ndim

2

In [7]:
a3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
#array Operation
a3*2

array([[24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [10]:
a3 ==23

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [27]:
a4=np.random.random((3,3))
a4=np.round(a4*10)
a4

array([[ 5.,  5.,  0.],
       [ 9.,  3.,  1.],
       [ 9., 10., 10.]])

In [30]:
#MIN MAX SUM PROD
np.sum(a4)

52.0

In [31]:
np.max(a4)

10.0

In [32]:
np.min(a4)

0.0

In [35]:
np.prod(a4,axis=1)

array([  0.,  27., 900.])

In [34]:
np.prod(a4,axis=0)

array([405., 150.,   0.])

In [36]:
#mean median std var
np.mean(a4)

5.777777777777778

In [37]:
np.median(a4)

5.0

In [38]:
np.var(a4)

13.506172839506172

In [39]:
np.std(a4)

3.675074535231384

In [40]:
#trigonomoetric function
np.sin(a4)

array([[-0.95892427, -0.95892427,  0.        ],
       [ 0.41211849,  0.14112001,  0.84147098],
       [ 0.41211849, -0.54402111, -0.54402111]])

In [41]:
#dot product
a5=np.arange(12).reshape(3,4)
a6=np.arange(12,24).reshape(4,3)
np.dot(a5,a6)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [42]:
#log and exponents
np.exp(a4)

array([[1.48413159e+02, 1.48413159e+02, 1.00000000e+00],
       [8.10308393e+03, 2.00855369e+01, 2.71828183e+00],
       [8.10308393e+03, 2.20264658e+04, 2.20264658e+04]])

In [43]:
np.log(a4)

<ipython-input-43-ba49b63410f2>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a4)


array([[1.60943791, 1.60943791,       -inf],
       [2.19722458, 1.09861229, 0.        ],
       [2.19722458, 2.30258509, 2.30258509]])